# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import books_service_pb2 as books__service__pb2


class BookServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListBooks = channel.unary_unary(
        '/BookService/ListBooks',
        request_serializer=books__service__pb2.Empty.SerializeToString,
        response_deserializer=books__service__pb2.ListBookResponse.FromString,
        )
    self.GetBook = channel.unary_unary(
        '/BookService/GetBook',
        request_serializer=books__service__pb2.GetBookRequest.SerializeToString,
        response_deserializer=books__service__pb2.BookResponse.FromString,
        )
    self.CreateBook = channel.unary_unary(
        '/BookService/CreateBook',
        request_serializer=books__service__pb2.CreateBookRequest.SerializeToString,
        response_deserializer=books__service__pb2.BookResponse.FromString,
        )
    self.EditBook = channel.unary_unary(
        '/BookService/EditBook',
        request_serializer=books__service__pb2.EditBookRequest.SerializeToString,
        response_deserializer=books__service__pb2.BookResponse.FromString,
        )
    self.DestroyBook = channel.unary_unary(
        '/BookService/DestroyBook',
        request_serializer=books__service__pb2.DestroyBookRequest.SerializeToString,
        response_deserializer=books__service__pb2.BookResponse.FromString,
        )


class BookServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListBooks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EditBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DestroyBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListBooks': grpc.unary_unary_rpc_method_handler(
          servicer.ListBooks,
          request_deserializer=books__service__pb2.Empty.FromString,
          response_serializer=books__service__pb2.ListBookResponse.SerializeToString,
      ),
      'GetBook': grpc.unary_unary_rpc_method_handler(
          servicer.GetBook,
          request_deserializer=books__service__pb2.GetBookRequest.FromString,
          response_serializer=books__service__pb2.BookResponse.SerializeToString,
      ),
      'CreateBook': grpc.unary_unary_rpc_method_handler(
          servicer.CreateBook,
          request_deserializer=books__service__pb2.CreateBookRequest.FromString,
          response_serializer=books__service__pb2.BookResponse.SerializeToString,
      ),
      'EditBook': grpc.unary_unary_rpc_method_handler(
          servicer.EditBook,
          request_deserializer=books__service__pb2.EditBookRequest.FromString,
          response_serializer=books__service__pb2.BookResponse.SerializeToString,
      ),
      'DestroyBook': grpc.unary_unary_rpc_method_handler(
          servicer.DestroyBook,
          request_deserializer=books__service__pb2.DestroyBookRequest.FromString,
          response_serializer=books__service__pb2.BookResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'BookService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
