# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='books_service.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x62ooks_service.proto\"\x07\n\x05\x45mpty\"\x1c\n\x0eGetBookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"(\n\x10ListBookResponse\x12\x14\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x05.Book\"(\n\x11\x43reateBookRequest\x12\x13\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.Book\"2\n\x0f\x45\x64itBookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x05.Book\" \n\x12\x44\x65stroyBookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"#\n\x0c\x42ookResponse\x12\x13\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.Book\"\\\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x01\x12\r\n\x05genre\x18\x05 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x06 \x01(\t2\xfb\x01\n\x0b\x42ookService\x12(\n\tListBooks\x12\x06.Empty\x1a\x11.ListBookResponse\"\x00\x12+\n\x07GetBook\x12\x0f.GetBookRequest\x1a\r.BookResponse\"\x00\x12\x31\n\nCreateBook\x12\x12.CreateBookRequest\x1a\r.BookResponse\"\x00\x12-\n\x08\x45\x64itBook\x12\x10.EditBookRequest\x1a\r.BookResponse\"\x00\x12\x33\n\x0b\x44\x65stroyBook\x12\x13.DestroyBookRequest\x1a\r.BookResponse\"\x00\x42\x14\n\x12net.gpedro.io-grpcb\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=30,
)


_GETBOOKREQUEST = _descriptor.Descriptor(
  name='GetBookRequest',
  full_name='GetBookRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetBookRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=60,
)


_LISTBOOKRESPONSE = _descriptor.Descriptor(
  name='ListBookResponse',
  full_name='ListBookResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='books', full_name='ListBookResponse.books', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=102,
)


_CREATEBOOKREQUEST = _descriptor.Descriptor(
  name='CreateBookRequest',
  full_name='CreateBookRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='book', full_name='CreateBookRequest.book', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=144,
)


_EDITBOOKREQUEST = _descriptor.Descriptor(
  name='EditBookRequest',
  full_name='EditBookRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='EditBookRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='book', full_name='EditBookRequest.book', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=196,
)


_DESTROYBOOKREQUEST = _descriptor.Descriptor(
  name='DestroyBookRequest',
  full_name='DestroyBookRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DestroyBookRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=230,
)


_BOOKRESPONSE = _descriptor.Descriptor(
  name='BookResponse',
  full_name='BookResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='book', full_name='BookResponse.book', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=267,
)


_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Book.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Book.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='year', full_name='Book.year', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='Book.price', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genre', full_name='Book.genre', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author', full_name='Book.author', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=361,
)

_LISTBOOKRESPONSE.fields_by_name['books'].message_type = _BOOK
_CREATEBOOKREQUEST.fields_by_name['book'].message_type = _BOOK
_EDITBOOKREQUEST.fields_by_name['book'].message_type = _BOOK
_BOOKRESPONSE.fields_by_name['book'].message_type = _BOOK
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['GetBookRequest'] = _GETBOOKREQUEST
DESCRIPTOR.message_types_by_name['ListBookResponse'] = _LISTBOOKRESPONSE
DESCRIPTOR.message_types_by_name['CreateBookRequest'] = _CREATEBOOKREQUEST
DESCRIPTOR.message_types_by_name['EditBookRequest'] = _EDITBOOKREQUEST
DESCRIPTOR.message_types_by_name['DestroyBookRequest'] = _DESTROYBOOKREQUEST
DESCRIPTOR.message_types_by_name['BookResponse'] = _BOOKRESPONSE
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'books_service_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

GetBookRequest = _reflection.GeneratedProtocolMessageType('GetBookRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETBOOKREQUEST,
  __module__ = 'books_service_pb2'
  # @@protoc_insertion_point(class_scope:GetBookRequest)
  ))
_sym_db.RegisterMessage(GetBookRequest)

ListBookResponse = _reflection.GeneratedProtocolMessageType('ListBookResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTBOOKRESPONSE,
  __module__ = 'books_service_pb2'
  # @@protoc_insertion_point(class_scope:ListBookResponse)
  ))
_sym_db.RegisterMessage(ListBookResponse)

CreateBookRequest = _reflection.GeneratedProtocolMessageType('CreateBookRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEBOOKREQUEST,
  __module__ = 'books_service_pb2'
  # @@protoc_insertion_point(class_scope:CreateBookRequest)
  ))
_sym_db.RegisterMessage(CreateBookRequest)

EditBookRequest = _reflection.GeneratedProtocolMessageType('EditBookRequest', (_message.Message,), dict(
  DESCRIPTOR = _EDITBOOKREQUEST,
  __module__ = 'books_service_pb2'
  # @@protoc_insertion_point(class_scope:EditBookRequest)
  ))
_sym_db.RegisterMessage(EditBookRequest)

DestroyBookRequest = _reflection.GeneratedProtocolMessageType('DestroyBookRequest', (_message.Message,), dict(
  DESCRIPTOR = _DESTROYBOOKREQUEST,
  __module__ = 'books_service_pb2'
  # @@protoc_insertion_point(class_scope:DestroyBookRequest)
  ))
_sym_db.RegisterMessage(DestroyBookRequest)

BookResponse = _reflection.GeneratedProtocolMessageType('BookResponse', (_message.Message,), dict(
  DESCRIPTOR = _BOOKRESPONSE,
  __module__ = 'books_service_pb2'
  # @@protoc_insertion_point(class_scope:BookResponse)
  ))
_sym_db.RegisterMessage(BookResponse)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), dict(
  DESCRIPTOR = _BOOK,
  __module__ = 'books_service_pb2'
  # @@protoc_insertion_point(class_scope:Book)
  ))
_sym_db.RegisterMessage(Book)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022net.gpedro.io-grpc'))

_BOOKSERVICE = _descriptor.ServiceDescriptor(
  name='BookService',
  full_name='BookService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=364,
  serialized_end=615,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListBooks',
    full_name='BookService.ListBooks',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_LISTBOOKRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBook',
    full_name='BookService.GetBook',
    index=1,
    containing_service=None,
    input_type=_GETBOOKREQUEST,
    output_type=_BOOKRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateBook',
    full_name='BookService.CreateBook',
    index=2,
    containing_service=None,
    input_type=_CREATEBOOKREQUEST,
    output_type=_BOOKRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EditBook',
    full_name='BookService.EditBook',
    index=3,
    containing_service=None,
    input_type=_EDITBOOKREQUEST,
    output_type=_BOOKRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DestroyBook',
    full_name='BookService.DestroyBook',
    index=4,
    containing_service=None,
    input_type=_DESTROYBOOKREQUEST,
    output_type=_BOOKRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOOKSERVICE)

DESCRIPTOR.services_by_name['BookService'] = _BOOKSERVICE

# @@protoc_insertion_point(module_scope)
